
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { productService } from '../services/database/productService.ts';
import { updateSupabaseConfig, isSupabaseConfigured, getSupabaseConfig } from '../lib/supabase.ts';
import Sales from './Sales';

interface DashboardProps {
  view: 'sales' | 'inventory' | 'stats' | 'config';
  setView: (v: 'sales' | 'inventory' | 'stats' | 'config') => void;
  stats: { totalRevenue: number; orderCount: number; avgTicket: number };
  onLogout: () => void;
}

const Dashboard: React.FC<DashboardProps> = ({ view, setView, stats, onLogout }) => {
  const [syncing, setSyncing] = useState(false);
  const { url: initialUrl, key: initialKey } = getSupabaseConfig();
  const [dbUrl, setDbUrl] = useState(initialUrl);
  const [dbKey, setDbKey] = useState(initialKey);

  const handleSync = async () => {
    setSyncing(true);
    try {
      const res = await productService.seedDatabase();
      alert(res.message);
      window.location.reload();
    } catch (err: any) {
      alert(`Erro: As tabelas não foram encontradas. Você rodou o SQL no painel do Supabase?`);
    } finally {
      setSyncing(false);
    }
  };

  const sqlSetup = `-- BACKEND DO SEU JOSÉ - EXECUTE NO SUPABASE
-- Vá em 'SQL Editor' -> 'New Query', cole e clique em 'Run'

-- Tabela de Produtos
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Usuários
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  cpf TEXT UNIQUE,
  phone TEXT,
  role TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir usuário demo (Seu José)
INSERT INTO users (id, name, email, cpf, phone, role)
VALUES ('00000000-0000-0000-0000-000000000001', 'Seu José', 'jose@mercadinho.com', '000.000.000-00', '(11) 99999-9999', 'owner')
ON CONFLICT (email) DO NOTHING;

-- Tabela de Pedidos
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  total DECIMAL NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_method TEXT,
  address JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Items do Pedido
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT,
  quantity INTEGER NOT NULL,
  price_at_time DECIMAL NOT NULL
);

-- Ativar Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DROP POLICY IF EXISTS "Public Read Products" ON products;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Products" ON products;
CREATE POLICY "Public Insert Products" ON products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Users" ON users;
CREATE POLICY "Public Read Users" ON users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Users" ON users;
CREATE POLICY "Public Insert Users" ON users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Create Orders" ON orders;
CREATE POLICY "Public Create Orders" ON orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Orders" ON orders;
CREATE POLICY "Public Read Orders" ON orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Update Orders" ON orders;
CREATE POLICY "Public Update Orders" ON orders FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Create Items" ON order_items;
CREATE POLICY "Public Create Items" ON order_items FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Items" ON order_items;
CREATE POLICY "Public Read Items" ON order_items FOR SELECT USING (true);`;

  return (
    <div className="pt-48 pb-24 px-6 max-w-7xl mx-auto">
      <div className="flex justify-center mb-16">
        <div className="glass border border-jose-dark/5 rounded-full px-4 py-2 flex items-center gap-1 shadow-xl overflow-x-auto no-scrollbar max-w-full">
          {['stats', 'sales', 'inventory', 'config'].map((v: any) => (
            <button 
              key={v}
              onClick={() => setView(v)} 
              className={`px-4 md:px-6 py-2 rounded-full text-[9px] md:text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap ${view === v ? 'bg-jose-dark text-white shadow-lg' : 'text-jose-dark/40 hover:text-jose-dark'}`}
            >
              {v === 'stats' ? 'Relatório' : v === 'sales' ? 'Vendas' : v === 'inventory' ? 'Estoque' : 'Config'}
            </button>
          ))}
          <div className="w-px h-4 bg-jose-dark/10 mx-2 shrink-0"></div>
          <button onClick={onLogout} className="px-4 py-2 text-[9px] md:text-[10px] font-black uppercase tracking-widest text-red-400 hover:text-red-600">Sair</button>
        </div>
      </div>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-12">
        {view === 'stats' && (
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-10 rounded-[3rem] shadow-xl border border-jose-dark/5 flex flex-col justify-between h-64">
              <p className="text-[11px] font-black uppercase text-jose-accent tracking-[0.3em]">Faturamento</p>
              <div className="flex items-baseline gap-2">
                <span className="text-2xl font-serif text-jose-primary">R$</span>
                <span className="text-6xl font-serif text-jose-dark leading-none tracking-tighter">{stats.totalRevenue.toLocaleString('pt-BR')}</span>
              </div>
            </div>
            <div className="bg-white p-10 rounded-[3rem] shadow-xl border border-jose-dark/5 flex flex-col justify-between h-64">
              <p className="text-[11px] font-black uppercase text-jose-accent tracking-[0.3em]">Conexão Supabase</p>
              <div className="flex flex-col gap-3">
                <div className="text-[10px] font-bold uppercase px-4 py-2 rounded-full bg-green-100 text-green-700 inline-block w-fit">
                  Ativa via Código ✓
                </div>
                <p className="text-[10px] text-gray-400">qwihgz...supabase.co</p>
              </div>
            </div>
            <div className="bg-jose-accent p-10 rounded-[3rem] shadow-xl text-white flex flex-col justify-between h-64">
              <p className="text-[11px] font-black uppercase tracking-[0.3em] opacity-60">Pedidos Hoje</p>
              <h3 className="text-7xl font-serif leading-none">{stats.orderCount}</h3>
            </div>
          </div>
        )}

        {view === 'config' && (
          <div className="grid lg:grid-cols-2 gap-8">
            <div className="bg-white p-12 rounded-[4rem] shadow-2xl border border-jose-dark/5">
              <h3 className="text-3xl font-serif text-jose-dark mb-4">Ajustes Técnicos</h3>
              <p className="text-gray-400 text-xs mb-8">Os links que você enviou já estão injetados no sistema. Só altere se mudar de projeto.</p>
              <div className="space-y-6">
                <div>
                  <label className="text-[9px] font-black uppercase tracking-widest text-jose-dark/40 block mb-2 ml-4">Project URL</label>
                  <input type="text" value={dbUrl} onChange={e => setDbUrl(e.target.value)} className="w-full p-5 bg-jose-light rounded-2xl outline-none border border-transparent focus:border-jose-accent transition-all text-sm" />
                </div>
                <div>
                  <label className="text-[9px] font-black uppercase tracking-widest text-jose-dark/40 block mb-2 ml-4">Anon Key</label>
                  <input type="password" value={dbKey} onChange={e => setDbKey(e.target.value)} className="w-full p-5 bg-jose-light rounded-2xl outline-none border border-transparent focus:border-jose-accent transition-all text-sm" />
                </div>
                <button onClick={() => updateSupabaseConfig(dbUrl, dbKey)} className="w-full bg-jose-dark text-white py-6 rounded-3xl font-black uppercase text-[10px] tracking-widest shadow-xl">Atualizar Chaves</button>
              </div>
            </div>

            <div className="bg-jose-dark p-12 rounded-[4rem] text-white shadow-2xl">
              <h3 className="text-3xl font-serif mb-4 text-jose-accent">Obrigatório</h3>
              <p className="text-white/50 text-xs mb-6">Você DEVE rodar esse código no SQL Editor do Supabase para o site carregar os produtos:</p>
              <div className="relative">
                <pre className="bg-black/40 p-6 rounded-2xl text-[9px] font-mono overflow-x-auto whitespace-pre max-h-[200px] text-green-400">
                  {sqlSetup}
                </pre>
                <button onClick={() => { navigator.clipboard.writeText(sqlSetup); alert("SQL Copiado!"); }} className="absolute top-4 right-4 bg-white/10 p-2 rounded-lg"><i className="fas fa-copy"></i></button>
              </div>
              <button disabled={syncing} onClick={handleSync} className="w-full mt-8 bg-jose-accent text-white py-6 rounded-3xl font-black uppercase text-[10px] tracking-widest">
                {syncing ? 'Processando...' : 'Criar Produtos Iniciais'}
              </button>
            </div>
          </div>
        )}

        {(view === 'sales' || view === 'inventory') && (
          <>
            {view === 'sales' && <Sales />}
            {view === 'inventory' && (
              <div className="bg-white p-20 rounded-[4rem] shadow-2xl border border-jose-dark/5 text-center">
                <h3 className="text-2xl font-serif text-jose-dark mb-4">Módulo Ativo</h3>
                <p className="text-gray-400 max-w-md mx-auto italic">Tudo pronto para o Seu José começar a vender.</p>
              </div>
            )}
          </>
        )}
      </motion.div>
    </div>
  );
};

export default Dashboard;
