-- BACKEND DO SEU JOSÉ - EXECUTE NO SUPABASE
-- Vá em 'SQL Editor' -> 'New Query', cole e clique em 'Run'

-- Tabela de Produtos
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Usuários
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  cpf TEXT UNIQUE,
  phone TEXT,
  role TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir usuário demo (Seu José)
INSERT INTO users (id, name, email, cpf, phone, role)
VALUES ('00000000-0000-0000-0000-000000000001', 'Seu José', 'jose@mercadinho.com', '000.000.000-00', '(11) 99999-9999', 'owner')
ON CONFLICT (email) DO NOTHING;

-- Tabela de Pedidos
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  total DECIMAL NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_method TEXT,
  address JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Items do Pedido
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT,
  quantity INTEGER NOT NULL,
  price_at_time DECIMAL NOT NULL
);

-- Ativar Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso para Products
DROP POLICY IF EXISTS "Public Read Products" ON products;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Products" ON products;
CREATE POLICY "Public Insert Products" ON products FOR INSERT WITH CHECK (true);

-- Políticas de Acesso para Users
DROP POLICY IF EXISTS "Public Read Users" ON users;
CREATE POLICY "Public Read Users" ON users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Users" ON users;
CREATE POLICY "Public Insert Users" ON users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Users" ON users;
CREATE POLICY "Public Update Users" ON users FOR UPDATE USING (true);

-- Políticas de Acesso para Orders
DROP POLICY IF EXISTS "Public Create Orders" ON orders;
CREATE POLICY "Public Create Orders" ON orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Orders" ON orders;
CREATE POLICY "Public Read Orders" ON orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Update Orders" ON orders;
CREATE POLICY "Public Update Orders" ON orders FOR UPDATE USING (true);

-- Políticas de Acesso para Order Items
DROP POLICY IF EXISTS "Public Create Items" ON order_items;
CREATE POLICY "Public Create Items" ON order_items FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Items" ON order_items;
CREATE POLICY "Public Read Items" ON order_items FOR SELECT USING (true);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
